### ISSUE TITLE
Cloning an assignment fails because of this mod

### ISSUE THREAD

**Issue by jolly-jump** [learnweb/moodle-assignsubmission_collabora#11]
Hi,

this is purely from trial and error. Please try to reproduce:
1. create an assignment adding collabora-submission (named or name randomly created does not matter) as a possibility
2. duplicate the assignment
3. try to edit the assignment - can't be done

Error: Call to a member function get_filename() on bool

**Comment by euneuber** [comment]
Any updates on this topic?

**Comment by grabs** [comment]
Hi Eugen,
I am sorry, I totally missed this. I will check this the next days.
Best regards
Andreas

**Comment by grabs** [comment]
Hi Eugen,
the new release is out.
Note: There is an new branching scheme.
The master now is only for Moodle/master.
For Moodle 3.9 und 3.10 is a branch MOODLE_39_STABLE
For Moodle 3.11 is a branch MOODLE_311_STABLE

This change was necessary due to a lot of differences between the versions related to automated testing.
Best regards
Andreas
